let pum = {
  scene: {
    setup: {
      expectation: [
        "Interrupted by a different scene prompt",
        "There is a complication",
        "Almost as expected",
        "Happens as expected",
        "Happens as expected",
        "Happens as expected",
        "Happens as expected",
        "Happens as expected",
        "Happens as expected",
        "Even better than what expected",
      ],
      prompt: [
        "There is a complication",
        "Invoke scene catalyst",
        "Problem or challenge",
        "Risk about to trigger",
        "Opportunity to make a discovery",
        "Social related encounter",
        "Consequence of your actions or presence",
        "Location specific event",
        "Discover enemy actions",
        "Face active opposition",
        "Trouble circumstance"
      ],
    },
    designer: {
      catalyst: [
        "History or past recalled",
        "Social event occurrence",
        "Setting aspect featured",
        "PCs backstories referred",
        "Location detail invoked",
        "Local faction activities",
        "An opportunity to trade",
        "Alternative route found",
        "Find something of use",
        "Call character strengths",
        "It's about to happen",
        "Be summoned or called",
        "An esoteric occult event",
        "Someone else's troubles",
        "Impacts of remote event",
        "Test for keen senses",
        "Change in environment",
        "Route or path blocked",
        "Character flaws recalled",
        "A danger is nearby..",
      ],
      challenge: [
        "Immediate healing or medicine required",
        "Have to endure, resist or withstand",
        "Strength, force or power can be of help",
        "Things here may take long time to solve",
        "Presence of magic, divine or technology",
        "Something hidden or hard to perceive",
        "An element is hard to reach out or get",
        "Job for a specialist or crafts expert",
        "Presence of guards, sentinels or security",
        "Have sanity, spirit or willpower tested",
        "Something to crack, unlock or enable",
        "Something needs protection or care",
        "Potentially hiding or ambushing actors",
        "Driving, piloting, handling to be done",
        "Charisma or a strong personality can help",
        "Requires keen senses or extreme intuition",
        "Something only for experts to understand",
        "Could use a soft hand, empathy or wisdom",
        "Something fails, breaks or needs repair",
        "Confronting or fighting might be a way out",
      ],
      circumstance: [
        "There is more trouble than expected",
        "Presence of special equipment or feats",
        "Deception, hazards or traps are laid out",
        "Information or knowledge is missing",
        "There is elevation or vertical terrain",
        "Location is dangerous or problematic",
        "Someone supporting from a distance",
        "Unexpected help or support is arriving",
        "Something needs to be done in parallel",
        "Time limit or intense pressure",
        "Presence of innocents or bystanders",
        "Location is moving or unstable",
        "There are atmospheric difficulties",
        "Tactical devices may be utilized",
        "Vehicle or machine can be utilized",
        "May have secret passages or routes",
        "Hidden presence sneaking or watching",
        "Luck or chance plays an important role",
        "Obstructing heavy or blocking elements",
        "Presence of invisible forces or powers",
      ],
      complication: [
        "Missing, Lost, Forgotten",
        "Delicate, Dangerous, Sensitive",
        "Blocked, Hidden, Trapped",
        "Problematic, Disastrous, Rebelled",
        "Dead, Destroyed, Unrecoverable",
        "Broken, Damaged, Injured",
        "Flooded, Overloaded, Exceeded",
        "Sabotaged, Captured, Taken",
        "Corrupted, Twisted, Cursed",
        "False, Fake, Corrupt, Concealed",
        "Mistaken, Discarded, Wrong",
        "Leaked, Discovered, Revealed",
        "Unreliable, Erratic, Insufficient",
        "Disrupted, Modified, Altered",
        "Concerning, Unsettling, Feared",
        "Useless, Abandoned, Obsolete",
        "Sick, Hazardous, Weak, Incapable",
        "Prepared, Defended, Ready",
        "Unprepared, Unarmed, Surprised",
        "Delayed, Late, Hindered",
      ],
      discovery: [
        "Answer one open question",
        "Meet or learn of someone",
        "Find something very useful",
        "New way to solve a thread",
        "Learn enemy action or plan",
        "Upcoming event or twist",
        "Learn more about a location",
        "Helpful for a relationship",
        "Confirm a hope or theory",
        "Discover enemy weakness",
      ],
      risk: [
        "Lose a trace or waste time",
        "Compromise someone else",
        "Lose or sacrifice something",
        "Be exposed to severe harm",
        "Expose weaknesses or plans",
        "Give enemy advantage",
        "Confirm a concern",
        "Harm a relationship",
        "Endanger an object",
        "End up in a fight",
      ],
      subject: [
        "Enemy",
        "Faction",
        "Plan",
        "Target",
        "Location",
        "Ally",
        "Being",
        "Object",
        "Information",
        "Ability",
      ],
    },
  },
  oracle: {
    yesorno: {
      even: [
        "Don't know",
        "Hard to say",
        "No",
        "No",
        "No",
        "No",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
      ],
      likely: [
        "Hard to say",
        "Don't know",
        "No",
        "No",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
      ],
      unlikely: [
        "Don't know",
        "Hard to say",
        "No",
        "No",
        "No",
        "No",
        "No",
        "No",
        "Yes",
        "Yes",
      ],
      modifier: [
        ", possibly.",
        ", for now.",
        ", but...",
        ".",
        ".",
        ".",
        ".",
        ", and...",
        ", unless...",
        ", obviously.",
      ]
    },
    what: {
      type: [
        "Known",
        "Sensitive",
        "Conflicting",
        "Valuable",
        "Surprising",
        "Personal",
        "Dangerous",
        "Own",
        "Secretive",
        "Unique",
      ],
      subject: [
        "Weakness",
        "Event",
        "Result",
        "Backstory",
        "Location",
        "Politics",
        "Business",
        "Encounter",
        "Decision",
        "Request",
      ],
      event: [
        "Sabotaged",
        "Exposed",
        "Discovered",
        "Opposed",
        "Destroyed",
        "Hindered",
        "Observed",
        "Removed",
        "Established",
        "Exploited",
      ],
    },
    who: {
      subject: [
        "An unimportant",
        "A strange",
        "A local",
        "An old",
        "A family related",
        "A scared",
        "An angry",
        "A desperate",
        "A powerful",
        "An important",
      ],
      type: [
        "ally",
        "ally",
        "ally",
        "person",
        "person",
        "person",
        "being",
        "enemy",
        "enemy",
        "enemy",
      ],
    },
    intent: {
      they: [
        "Fight",
        "Oppose",
        "Demand",
        "Request",
        "Need",
        "Offer",
        "Explain",
        "Join",
        "Trade",
        "Help",
      ],
      subject: [
        "enemies",
        "allies",
        "cause",
        "situation",
        "object",
        "location",
        "information",
        "plans",
        "resources",
        "power",
      ],
    },
    activity: {
      they: [
        "Claiming",
        "Supporting",
        "Searching",
        "Preparing",
        "Hindering",
        "Holding",
        "Requesting",
        "Controlling",
        "Attacking",
        "Expelling",
      ],
      subject: [
        "business",
        "authority",
        "place",
        "faction",
        "someone",
        "defense",
        "knowledge",
        "words",
        "resources",
        "agreement",
      ],
    },
    reason: {
      action: [
        "Seek",
        "Recover",
        "Controlling",
        "Matter of",
        "Need",
        "Eradicate",
        "Deal with",
        "Desire",
        "Secure",
        "Prevent",
      ],
      motive: [
        "power or status",
        "revenge or a debt",
        "glory or reputation",
        "chaos or destruction",
        "culture or history",
        "knowledge or interest",
        "contract or an order",
        "justice or rights",
        "safety or survival",
        "resources or wealth",
      ],
    },
    describe: {
      adverb: [
        "Curiously",
        "Specially",
        "Defensively",
        "Knowlingly",
        "Strongly",
        "Legally",
        "Actively",
        "Commonly",
        "Mostly",
        "Incredibly",
      ],
      area: [
        "Ruined",
        "Ancient",
        "Abandoned",
        "Dangerous",
        "Empty",
        "Unusual",
        "Secure",
        "Crowded",
        "Fancy",
        "Fortified",
      ],
      someone: [
        "Injured",
        "Clever",
        "Hunted",
        "Dangerous",
        "Skilled",
        "Exotic",
        "Innocent",
        "Famous",
        "Rich",
        "Powerful",
      ],
      object: [
        "Broken",
        "Antique",
        "Forbidden",
        "Dangerous",
        "Mundane",
        "Rare",
        "Harmless",
        "Legendary",
        "Valuable",
        "Reinforced",
      ],
    },
    kind_of: {
      item: [
        "Healing",
        "Deadly",
        "Ingest",
        "Protect",
        "Mystic",
        "Tech",
        "Historic",
        "Divine",
        "Move",
        "Static",
      ],
      ability: [
        "Absorb",
        "Harmful",
        "Utility",
        "Elemental",
        "Enhance",
        "Natural",
        "Weaken",
        "Tiring",
        "Healing",
        "Support",
      ],
      people: [
        "Fighter",
        "Medical",
        "Civilian",
        "Scavenger",
        "Academic",
        "Faithful",
        "Powerful",
        "Craftsmen",
        "Wealthy",
        "Enforcing",
      ],
      enemy: [
        "Agile",
        "Defend",
        "Sneaky",
        "Native",
        "Smart",
        "Magical",
        "Animal",
        "Artificial",
        "Gigantic",
        "Horrible",
      ],
      danger: [
        "Trap",
        "Explode",
        "Corrode",
        "Terrain",
        "Enemy",
        "Run",
        "Secret",
        "Sound",
        "Damage",
        "Hide",
      ],
    },
  },
};
